---
title: "EDA: group and summarize"
output: github_document
---


```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(ggridges)
library(viridis)
library(patchwork)
```

load in a dataset
```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>% # create a new column "month" that round down the date to the first day of the week
  select(name, id, everything())
```
```{r}
weather_df
```
```{r}
weather_df %>% 
  group_by(name, month)  # group_by(name) or group_by(month)
```
## count some things 
```{r}
weather_df %>% 
  group_by(month) %>% # you can also group by (name,month)
  summarize(n_abs = n())  # count how many observations during each month
# you can use count()
```
## It's nice that summarize produces a data frame
`table` will not simply work
```{r, eval = FALSE}
weather_df %>% 
  pull(mean) %>% 
  table()
```
```{r}
weather_df %>% 
  janitor::tabyl(month, name)  # useful way to present the result, better than table()
```

## more general summaries
count, takes means, look at SDs...
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
  geom_point(alpha = 0.5) + 
  geom_line()
```
Formatting tibble outputs
```{r}
weather_df %>%
  group_by(name) %>% 
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
  ) %>%
  knitr::kable(digits = 2)  # round 2 digits
```
## grouped `mutate`
```{r}
weather_df %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE) # just compute the mean of everythig
  )
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE) # compute the mean of the group
  )
```
```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point()
```

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    tmax_rank = min_rank(desc(tmax))  # get the maximum temperature 
  ) %>% 
  filter(tmax_rank<2)
```
Lagged variable
```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    lagged_tmax = lag(tmax, n = 1), # the data from the previous day or previous n days
    tmax_diff = tmax - lagged_tmax
  ) %>% 
  summarize(diff_sd = sd(tmax_diff, na.rm = TRUE))
```

## limitations
what if my "summary" is a linear model?
```{r}
weather_df %>% 
  group_by(name) %>% 
  summarize(cor_tmin_max = cor(tmin, tmax, use = "complete"))

weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  lm(tmax ~ tmin, data = .)

#weather_df %>% 
#  group_by(name) %>% 
#  summarize(lm = lm(tmax~tmin)) # cant have a vector with linear models
```








