---
title: "ggplot 2"
output: github_document
---


```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(ggridges)
library(viridis)
library(patchwork)
```

load in a dataset
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(  # download the dataset 
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), # pick three variabels that you care about
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%  # from 20170101 to 20171231
  mutate(
    name = recode(  # create a new name variable that recode the weather station
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
```{r}
weather_df
```

Start making some plots
# Scatterplot
tmax vs. tmin in a scatterplot
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  labs(
    title = "Temperature at Three station",
    x = "Minimum daily temp (C)",
    y = "Maximum daily temp (C)",
    caption = "Data from moaa package with three stations"
  )
```
## Scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.3) + 
  labs(
    title = "Temperature at Three station",
    x = "Minimum daily temp (C)",
    y = "Maximum daily temp (C)",
    caption = "Data from moaa package with three stations"
  ) + 
  scale_x_continuous(  # continuous variable on the x axis
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15")
  ) + 
  scale_y_continuous(
    trans = "sqrt",  # sqrt transformation
    position = "right"
  )
```
Color scales
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) + 
  labs(
    title = "Temperature at Three station",
    x = "Minimum daily temp (C)",
    y = "Maximum daily temp (C)",
    caption = "Data from moaa package with three stations"
  ) + 
  #scale_color_hue(h = c(100, 300))
  scale_color_viridis_d()  # d for discrete variable 
```
## Themes
aren't scale/ mapping related, but just to make plots look nicer
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.5) + 
  labs(
    title = "Temperature at Three station",
    x = "Minimum daily temp (C)",
    y = "Maximum daily temp (C)",
    caption = "Data from moaa package with three stations"
  ) + 
  scale_color_viridis_d() +
  theme_minimal() + # change background theme to bw/ classic/ minimal
  #ggthemes::theme_excel() + # graphs look like coming right from excel
  theme(legend.position = "bottom")
```
you can also set global features, codes in www.p8105.com

## `data` in geoms
```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")
waikiki %>% 
  ggplot(aes(x = date, y = tmax, color = name )) +
  geom_point() +
  geom_line(data = central_park)
```

## `patchwork`
```{r}
ggp_tmax_tmin = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.5) +
  theme(legend.position = "none")

ggp_prep_dens = 
  weather_df %>% 
  filter(prcp > 0) %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.3) +
  theme(legend.position = "none")  # get rid of the legends

ggp_tmax_date = 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth() +
  theme(legend.position = "none")
(ggp_tmax_tmin + ggp_prep_dens) / ggp_tmax_date  # patchwork will stuff graphs together, "/" will put this underneath
```

## data manipulation
quick example on factors
```{r}
weather_df %>% 
  mutate(
    name = fct_reorder(name, tmax)  # put in order of tmax from low to high
  ) %>% 
  #mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
  #geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
```
what about tmax and tmin? density plot
```{r}
weather_df %>%
  select(name, tmax, tmin) %>% 
  pivot_longer(
    tmax:tmin,
    names_to = "observation", 
    values_to = "temp") %>% 
  ggplot(aes(x = temp, fill = observation)) +
  geom_density(alpha = .5) + 
  facet_grid(~name) + 
  viridis::scale_fill_viridis(discrete = TRUE)
```
```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score_"
  ) %>% 
  mutate(visit = recode(visit, "bl" = "00m"))
pulse_df %>% 
  ggplot(aes(x = visit, y = bdi)) +
  #geom_boxplot()
  geom_point() +
  geom_line(aes(group = id))  # connect the dots, good for longitudinal data analysis
```
```{r}

```



