---
title: "ggplot 1"
output: github_document
---


```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(ggridges)
```

load in a dataset
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(  # download the dataset 
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), # pick three variabels that you care about
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%  # from 20170101 to 20171231
  mutate(
    name = recode(  # create a new name variable that recode the weather station
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
```{r}
weather_df
```

Start making some plots
# Scatterplot
tmax vs. tmin in a scatterplot
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + # the first argument should be the df ?
  geom_point()
```
you can save ggplots
```{r}
gg_tmax_tmin = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + # the first argument should be the df ?
  geom_point()

gg_tmax_tmin # you can add geometry to this object
```

## Add more details/ fancy it up
add color? lines? other stuff?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + # straightforward explanation
  geom_point( alpha = 0.3) +  # alpha = 0: transparent, = 1: opaque, but the line is left along. you can set the geometry specific aesthetic by adding the aes() here or in ggplot() function (this will be global)
  geom_smooth(se = FALSE) + # add three different lines showing the middle of the data set (nonlinear), Display confidence interval around smooth? 
  facet_grid(. ~ name) # spread things out, the dot: don't want to separate the rows, just give me three separate columns
```




